
services:
  users-service:
    build: ./services/users-service
    ports:
      - "3001:3000"

  products-service:
    build: ./services/products-service
    container_name: products-service
    ports:
      - "3002:3000"

  orders-service:
    build: ./services/orders-service
    container_name: orders-service
    ports:
      - "3003:3000"
    depends_on:
      - products-service

  payments-service:
    build: ./services/payments-service
    ports:
      - "3004:3000"

  frontend:
    build: ./services/frontend
    ports:
      - "3005:3000"
    depends_on:
      - products-service
      - orders-service

